<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS02_Deposit or Withdraw THEN Check Balance THEN check mini Statement</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>02904162-5ac5-48d4-a04d-7159cda35d23</testSuiteGuid>
   <testCaseLink>
      <guid>071dc69a-2ff2-40a0-9cb6-2b37095b5f8d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Folder_03_Deposit_Withdrawal/TC02_Deposit or Withdraw THEN Check Balance THEN Check Mini Statement</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0d3fe781-d20f-450a-a8bf-8fbb4b98dcca</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Deposit-Withdrawal</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>0d3fe781-d20f-450a-a8bf-8fbb4b98dcca</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>type</value>
         <variableId>b9b354d7-b2fb-4852-8ed9-bb6a49daed74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0d3fe781-d20f-450a-a8bf-8fbb4b98dcca</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>accountID</value>
         <variableId>096bf31b-99ed-472e-827d-afdc2a4a49bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0d3fe781-d20f-450a-a8bf-8fbb4b98dcca</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>amount</value>
         <variableId>5abe24d0-b2a7-4509-bd1d-c07b037d9f1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0d3fe781-d20f-450a-a8bf-8fbb4b98dcca</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>description</value>
         <variableId>b68e707c-6625-44e0-b983-77d2a5b8b9ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61f09551-7bfe-477e-885b-71cd97d23ea2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d59b9a4-5439-4a88-931f-b4dba0df6cfd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
