<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Deposit or Withdraw then Verify by Balance Enquiry</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ceed5653-5d44-4d18-b0a4-3a4f407f27ea</testSuiteGuid>
   <testCaseLink>
      <guid>d91ab700-7de3-4499-ad9e-722396cf53e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test Flow/Flow 5 - Deposit or Withdraw then Verify/Deposit or Withdraw then Verify by Balance Enquiry</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0e952500-e9f3-4e6d-8728-e4a6d68eedba</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Deposit-Withdrawal</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>0e952500-e9f3-4e6d-8728-e4a6d68eedba</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>type</value>
         <variableId>8ec2609d-4b8f-4485-aec2-2ee450fad25a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0e952500-e9f3-4e6d-8728-e4a6d68eedba</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>accountID</value>
         <variableId>51f0173f-c2c5-4505-93d7-fdc6dbdcd03d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0e952500-e9f3-4e6d-8728-e4a6d68eedba</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>amount</value>
         <variableId>248a96e0-1bc9-4818-8969-df05d37f5ae4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0e952500-e9f3-4e6d-8728-e4a6d68eedba</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>description</value>
         <variableId>7165191b-8d17-41af-b018-5bac8efb913b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea7c4e5d-4dd2-48e3-bac1-008e9e22ffa9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
